### ISSUE TITLE
Clarify license?

### ISSUE THREAD

**Issue by dirkmueller** [robotpy/fakearmv7l#1]
Could you please make a license declaration under which this code is available?

**Comment by virtuald** [comment]
Unfortunately, the website that I pulled it from doesn't state a license, so I'm reluctant to add my own.

**Comment by dirkmueller** [comment]
Thanks for the quick answer. If you don't claim your own copyright, could you please add the link to the original author or website? Maybe it is simply public domain then, which would be the easiest.

**Comment by virtuald** [comment]
It's in the README already.

**Comment by dirkmueller** [comment]
D'oh, got confused by the automatic shortening of the readme by github!
